/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./scalajs-modules/*.js"],
  theme: {
    colors: {
      "gray-0": "#FFFFFF",
      "gray-1": "#F9FAFB",
      "gray-2": "#EDEFF2",
      "gray-3": "#E7E9ED",
      "gray-4": "#CCD2DB",
      "gray-5": "#98A1B2",
      "gray-6": "#8790A4",
      "gray-7": "#646E82",
      "gray-8": "#323C4D",
      "gray-9": "#1D2939",
      "danger-1": "#F8E8E8",
      "danger-2": "#F6C4C4",
      "danger-3": "#F27777",
      "danger-4": "#E32D2D",
      "danger-5": "#CB0808",
      "primary-1": "#DCF2FA",
      "primary-2": "#AADAF9",
      "primary-3": "#48AFF0",
      "primary-4": "#1075DC",
      "primary-5": "#0158AE",
      "success-1": "#CEF2D5",
      "success-2": "#9DE5AB",
      "success-3": "#38B95E",
      "success-4": "#239E47",
      "success-5": "#1F7931",
      "warning-1": "#FEEFCB",
      "warning-2": "#FCDEA4",
      "warning-3": "#FFB829",
      "warning-4": "#DE990F",
      "warning-5": "#8C6500",
      transparent: "transparent",
      current: "currentColor",
      inherit: "inherit",
      "custom-1": "var(--color-custom-1)",
      "custom-2": "var(--color-custom-2)",
      "custom-3": "var(--color-custom-3)",
      "custom-4": "var(--color-custom-4)",
    },
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
    },
    fontFamily: {
      sans: [
        "system-ui", // Chrome, New Edge & Safari on all platforms
        "-apple-system", // Firefox on Mac
        "Roboto", // Firefox on Android
        "Oxygen",
        "Cantarell",
        "Ubuntu", // Firefox on Linux
        "Segoe UI", // Firefox and Old Edge on Windows
        "sans-serif", // Super fallback
      ],
      mono: ["monospace"],
    },
    fontSize: {
      35: "35px",
      30: "30px",
      26: "26px",
      23: "23px",
      20: "20px",
      17: "17px",
      15: "15px",
      13: "13px",
      11: "11px",
      10: "10px",
      9: "9px",
      "custom-1": "var(--text-custom-1)",
    },
    fontWeight: {
      normal: 400,
      medium: 500,
      "semi-bold": 600,
      bold: 700,
    },
    inset: {
      0: "0px",
    },
    lineHeight: {
      16: "16px",
      20: "20px",
      24: "24px",
      28: "28px",
      32: "32px",
      40: "40px",
      44: "44px",
      r1p5: "1.5",
    },
    borderWidth: {
      default: "1px",
      3: "3px",
    },
    borderRadius: {
      0: "0",
      2: "2px",
      3: "3px",
      4: "4px",
      6: "6px",
      8: "8px",
      full: "9999px",
    },
    width: {
      px1: "1px",
      px8: "8px",
      px16: "16px",
      px20: "20px",
      px24: "24px",
      px32: "32px",
      px40: "40px",
      px48: "48px",
      px64: "64px",
      px128: "128px",
      px256: "256px",
      px480: "480px",
      px512: "512px",
      px640: "640px",
      px768: "768px",
      px1024: "1024px",
      px1536: "1536px",
      pc10: "10%",
      pc20: "20%",
      pc25: "25%",
      pc30: "30%",
      pc33: "calc(100% / 3)",
      pc40: "40%",
      pc50: "50%",
      pc60: "60%",
      pc66: "calc(100% / 1.5)",
      pc70: "70%",
      pc75: "75%",
      pc80: "80%",
      pc90: "90%",
      pc100: "100%",
      auto: "auto",
      min: "min-content",
      max: "max-content",
      fit: "fit-content",
      "custom-1": "var(--width-custom-1)",
      "custom-2": "var(--width-custom-2)",
      "custom-3": "var(--width-custom-3)",
    },
    height: {
      px1: "1px",
      px8: "8px",
      px16: "16px",
      px20: "20px",
      px24: "24px",
      px32: "32px",
      px40: "40px",
      px48: "48px",
      px64: "64px",
      px128: "128px",
      px256: "256px",
      pc100: "100%",
      vh100: "100vh",
      auto: "auto",
      min: "min-content",
      max: "max-content",
      "custom-1": "var(--height-custom-1)",
      "custom-2": "var(--height-custom-2)",
      "custom-3": "var(--height-custom-3)",
    },
    minWidth: {
      fit: "fit-content",
      min: "min-content",
      max: "max-content",
    },
    minHeight: {
      pc100: "100%",
      vh100: "100vh",
    },
    maxWidth: {
      px128: "128px",
      px256: "256px",
      px480: "480px",
      px512: "512px",
      px640: "640px",
      px768: "768px",
      px1024: "1024px",
      pc100: "100%",
      "custom-1": "var(--max-width-custom-1)",
      "custom-2": "var(--max-width-custom-2)",
      "custom-3": "var(--max-width-custom-3)",
    },
    padding: {
      0: "0",
      2: "2px",
      4: "4px",
      6: "6px",
      8: "8px",
      12: "12px",
      16: "16px",
      20: "20px",
      24: "24px",
      32: "32px",
      40: "40px",
      48: "48px",
    },
    margin: {
      auto: "auto",
      0: "0",
      2: "2px",
      4: "4px",
      6: "6px",
      8: "8px",
      12: "12px",
      16: "16px",
      20: "20px",
      24: "24px",
      32: "32px",
      40: "40px",
      48: "48px",
    },
    boxShadow: {
      1: "0px 1px 2px rgba(29, 41, 57, 0.07)",
      2: "0px 1px 2px rgba(29, 41, 57, 0.04), 0px 2px 8px rgba(29, 41, 57, 0.08)",
      3: "0px 2px 8px rgba(29, 41, 57, 0.08), 0px 8px 24px rgba(29, 41, 57, 0.12)",
      4: "0px 4px 8px rgba(29, 41, 57, 0.08), 0px 16px 48px rgba(29, 41, 57, 0.16)",
    },
    zIndex: {
      auto: "auto",
      0: 0,
      1: 1,
      2: 2,
      3: 3,
      4: 4,
      5: 5,
      999: 999,
      9999: 9999,
    },
    opacity: {
      100: " 1",
      90: ".9",
      80: ".8",
      70: ".7",
      60: ".6",
      50: ".5",
      40: ".4",
      30: ".3",
      20: ".2",
      10: ".1",
      0: " 0",
    },
    spacing: {
      0: "0",
      2: "2px",
      4: "4px",
      6: "6px",
      8: "8px",
      12: "12px",
      16: "16px",
      20: "20px",
      24: "24px",
      32: "32px",
      40: "40px",
      48: "48px",
    },

    extend: {},
  },
  corePlugins: {
    accessibility: false,
    alignContent: false,
    alignSelf: false,
    animation: false,
    appearance: false,
    backdropBlur: false,
    backdropBrightness: false,
    backdropContrast: false,
    backdropFilter: false,
    backdropGrayscale: false,
    backdropHueRotate: false,
    backdropInvert: false,
    backdropOpacity: false,
    backdropSaturate: false,
    backdropSepia: false,
    backgroundAttachment: false,
    backgroundBlendMode: false,
    backgroundImage: false,
    backgroundPosition: false,
    backgroundRepeat: false,
    backgroundSize: false,
    blur: false,
    borderCollapse: false,
    borderOpacity: true,
    borderWidth: true,
    boxDecorationBreak: false,
    clear: false,
    content: true,
    contrast: false,
    dropShadow: false,
    fill: false,
    filter: false,
    float: false,
    fontVariantNumeric: true,
    gap: true,
    gradientColorStops: false,
    grayscale: false,
    gridAutoColumns: false,
    gridAutoFlow: false,
    gridAutoRows: false,
    gridColumn: false,
    gridColumnStart: false,
    gridColumnEnd: false,
    gridRow: false,
    gridRowStart: false,
    gridRowEnd: false,
    gridTemplateColumns: true,
    gridTemplateRows: false,
    hueRotate: false,
    invert: false,
    justifySelf: false,
    listStylePosition: false,
    listStyleType: false,
    maxHeight: false,
    mixBlendMode: false,
    negativeMargin: false,
    objectFit: false,
    objectPosition: false,
    order: false,
    outline: false,
    overscrollBehavior: false,
    placeholderColor: false,
    placeholderOpacity: false,
    placeContent: false,
    placeItems: false,
    placeSelf: false,
    preflight: false,
    ringColor: false,
    ringOffsetColor: false,
    ringOffsetWidth: false,
    ringOpacity: false,
    ringWidth: false,
    rotate: false,
    saturate: false,
    scale: false,
    sepia: false,
    skew: false,
    space: true,
    stroke: false,
    strokeWidth: false,
    tableLayout: false,
    transform: false,
    transformOrigin: false,
    translate: false,
    letterSpacing: false,
    transitionDelay: false,
    transitionDuration: false,
    transitionProperty: false,
  },
  plugins: [
  ],
};
