name: Integration Test

on:
  pull_request:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: Integration Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      # - uses: coursier/cache-action@v6
      - uses: VirtusLab/scala-cli-setup@main
        with:
          jvm: adopt:11
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install Dependencies & Build & Test Generator
        run: |
          pnpm install
          pnpm build
          pnpm test

      - name: Register Link Package
        run: bun link
        working-directory: ./packages/scalawind

      - name: Integration Test
        run: |
          bun install
          bun generate
          scala-cli test src
        working-directory: ./integration

      - name: Camelcase Integration Test
        run: |
          bun install
          bun generate
          scala-cli test src
        working-directory: ./camelcase-integration
