name: Snapshot Release

on:
  push:
    branches:
      - snapshot

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Snapshot Release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Install Dependencies
        run: |
          pnpm install

      - name: Build
        run: |
          pnpm build
          cp README.md packages/scalawind/README.md

      - name: Snapshot Release
        run: |
          pnpm release:snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}